In [1]:
import numpy as np

In [2]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [4]:
b= np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
c= np.zeros((2,3,4))
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.78147644e-307]])

In [9]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])